<?php
// Get the most recent IWP-generated report for a site, or list available schedules
// Usage: php generate-report.php <siteID>
//
// Returns the URL of the most recent report if one exists for this site.
// Reports are generated by IWP's Phoenix template system.

if (!defined('APP_ROOT')) define('APP_ROOT', dirname(__FILE__) . '/../..');
require_once(APP_ROOT . '/config.php');

$siteId = (int)($argv[1] ?? 0);
if (!$siteId) { echo json_encode(['error' => 'Site ID required']); exit(1); }

$db = new mysqli($config['SQL_HOST'], $config['SQL_USERNAME'], $config['SQL_PASSWORD'], $config['SQL_DATABASE'], (int)$config['SQL_PORT']);
$db->set_charset('utf8mb4');
$prefix = $config['SQL_TABLE_NAME_PREFIX'];

$site = $db->query("SELECT siteID, name, URL FROM {$prefix}sites WHERE siteID = $siteId")->fetch_assoc();
if (!$site) { echo json_encode(['error' => "Site $siteId not found"]); exit(1); }

// Find schedules that include this site
$matchingSchedules = [];
$allSchedules = $db->query("SELECT clientReportScheduleID, profileName, params, paused
    FROM {$prefix}client_report_schedule WHERE version = 'phoenix'");

while ($sched = $allSchedules->fetch_assoc()) {
    $params = @unserialize(@base64_decode($sched['params']));
    if ($params && in_array($siteId, $params['siteID'] ?? [])) {
        $matchingSchedules[] = $sched;
    }
}

// Find the most recent report for any matching schedule
$reportUrl = null;
$reportTime = null;
$scheduleUsed = null;

foreach ($matchingSchedules as $ms) {
    $report = $db->query("SELECT pdfURL, sentTime FROM {$prefix}client_report_sent_pdf
        WHERE clientReportScheduleID = {$ms['clientReportScheduleID']}
        ORDER BY sentTime DESC LIMIT 1")->fetch_assoc();

    if ($report && (!$reportTime || $report['sentTime'] > $reportTime)) {
        $pdfUrl = @unserialize(@base64_decode($report['pdfURL']));
        if (!$pdfUrl) $pdfUrl = $report['pdfURL'];

        // Verify the file exists
        $filePath = APP_ROOT . '/uploads/' . $pdfUrl;
        if (file_exists($filePath)) {
            $reportUrl = 'https://' . APP_DOMAIN_PATH . 'uploads/' . $pdfUrl;
            $reportTime = $report['sentTime'];
            $scheduleUsed = $ms['profileName'];
        }
    }
}

if ($reportUrl) {
    $age = time() - $reportTime;
    $ageLabel = $age < 3600 ? round($age / 60) . ' minutes' :
        ($age < 86400 ? round($age / 3600) . ' hours' : round($age / 86400) . ' days');

    echo json_encode([
        'success' => true,
        'url' => $reportUrl,
        'site' => $site['name'],
        'generatedAt' => date('Y-m-d H:i', $reportTime),
        'age' => $ageLabel,
        'schedule' => $scheduleUsed,
        'scheduleCount' => count($matchingSchedules)
    ]);
} else {
    // No report found - list available schedules
    $scheduleInfo = array_map(fn($s) => [
        'id' => $s['clientReportScheduleID'],
        'name' => $s['profileName'],
        'paused' => (bool)$s['paused']
    ], $matchingSchedules);

    echo json_encode([
        'success' => false,
        'site' => $site['name'],
        'message' => 'No report found for this site.',
        'schedules' => $scheduleInfo,
        'hint' => count($matchingSchedules) > 0
            ? 'There are schedules but no reports have been generated yet. Use "Run Now" in the IWP panel.'
            : 'No report schedule exists for this site. Create one in the IWP panel under Client Reporting.'
    ]);
}

$db->close();
